### ISSUE TITLE
How does your espanso to Texpand script work?

### ISSUE THREAD

**Issue by riotrah** [quintrino/dotfiles#3]
Hi! Been looking around a while for something like this. 

I'm not familiar with that syntax, esp without the file extension, nor Fresh if it's specific to that (I use chezmoi).

If you have the time, I'd love to know what your setup is for this. In particular, I'm curious how you utilize your dotfiles on Android - my hunch is that you've got some cloud sync going here, which is what I do for Espanso. 

Anyways, thanks for keeping this public!

**Comment by quintrino** [comment]
Hi @riotrah I seem to have missed a notification for this, but I'll answer just in case you're still curious. 

The espanso_to_texpand file was written to take all the espanso yml files in my /espanso/user/ folder (and my default.yml) and convert them using ruby erb into a csv file that was then force copied into a folder that was synced with Google Drive and then the android app [autosync](https://play.google.com/store/apps/details?id=com.ttxapps.drivesync) would copy it across to my phone. 

I would then have to manually import the csv file into Texpand. 

I've since switched to using [Expandroid](https://play.google.com/store/apps/details?id=com.dingleinc.texttoolspro) which just imports espanso formats automatically.

Happy to answer any questions you may have about it!
